// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Environment variabelen met fallback voor development
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  "https://uhrwgjwgdgpgrzbdodgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVocndnandnZGdwZ3J6YmRvZGdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDk1MDgsImV4cCI6MjA2OTE4NTUwOH0.GrgI-4xwg66tfBBNIjkil5nNEqawiPHMBcBRETM1sBU";

// Waarschuw voor ontbrekende environment variabelen in productie
if (import.meta.env.PROD) {
  if (!import.meta.env.VITE_SUPABASE_URL) {
    console.warn(
      "⚠️  VITE_SUPABASE_URL environment variabele niet gevonden, gebruik fallback"
    );
  }
  if (!import.meta.env.VITE_SUPABASE_ANON_KEY) {
    console.warn(
      "⚠️  VITE_SUPABASE_ANON_KEY environment variabele niet gevonden, gebruik fallback"
    );
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
